<div id="welcomeheader" class="navbar-default">
	<div class="container">
		<div class="logo <?php echo Wo_RightToLeft('pull-left');?>">
			<a href="<?php echo $wo['config']['site_url'];?>"><img width="50px" src="<?php echo $wo['config']['theme_url'];?>/img/logo.png" alt="Logo"> </a>
		</div>
		<?php if ($wo['config']['user_registration'] == 1): ?>
			<ul class="nav navbar-nav navbar-right <?php echo Wo_RightToLeft('pull-right');?>">
				<li class="absul-right">
					<a class="mdbtn" style="color: #ffffff;" href="<?php echo $wo['config']['site_url'];?>"><?php echo $wo['lang']['login']?></a>
				</li>
			</ul>
		<?php endif ?>
	</div>
</div>