<style>
    .header-container{
        display: none;
    }
</style>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<div style="text-align: center;font-size: 72px;">
    <span class="glyphicon glyphicon-refresh glyphicon-refresh-animate invite-loader"></span>
</div>
<div style="display: none;">
<!--    --><?php //echo Wo_LoadPage('welcome/welcome-header-register'); ?>
    <div class="wrapper">
        <div class="typing-element"></div>
        <div class="login fadeInUp animated animated_5">
            <div class="col-md-6">
                <form id="login" class="fadeInUp animated animated_9" method="post">
                    <p class="title"><?php echo $wo['lang']['login'] ?></p>
                    <div class="errors"></div>
                    <div class="wow_form_fields">
                        <label for="username"><?php echo $wo['lang']['username'] ?></label>
                        <input id="username" name="username"
                               value="<?php echo $wo['user_info']['username']; ?>" type="text"
                               autocomplete="off" autofocus>
                    </div>
                    <div class="wow_form_fields">
                        <label for="password"><?php echo $wo['lang']['password'] ?></label>
                        <input id="password" name="password" value="<?php echo $wo['rev_password'] ?>" type="password"
                               autocomplete="off">
                    </div>
                    <div class="forgot_password">
                        <a href="<?php echo Wo_SeoLink('index.php?link1=forgot-password'); ?>"><?php echo $wo['lang']['forget_password'] ?></a>
                    </div>
                    <div class="login_signup_combo">
                        <div class="login__">
                            <button type="submit"
                                    class="btn btn-main btn-mat btn-mat-raised add_wow_loader"><?php echo $wo['lang']['login'] ?></button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!--<div class="container">--><?php //echo Wo_LoadPage('footer/welcome');?><!--</div>-->
</div>

<script>
    var working = false;
    var $this = $('#login');
    var $state = $this.find('.errors');


    $('#login').on('submit', function (e) {
        e.preventDefault();
        $.ajax({
                type: "POST",
                url: Wo_Ajax_Requests_File() + '?f=login',
                data: $this.serialize(),
                beforeSend: function () {
                    working = true;
                    $this.find('button').attr("disabled", true);
                    $this.find('.add_wow_loader').addClass('btn-loading');
                },
                success: function (data) {

                    if (data.status == 200 || data.status == 600) {
                        $state.addClass('success');
                        $state.html('<?php echo $wo['lang']['welcome_back'] ?>');
                        $this.find('.add_wow_loader').removeClass('btn-loading');
                        setTimeout(function () {
                            window.location.href = data.location;
                        }, 1000);
                    } else {
                        var errors = data.errors.join("<br>");
                        $this.find('button').attr("disabled", false);
                        $this.find('.add_wow_loader').removeClass('btn-loading');
                        $state.html(errors);
                    }
                    working = false;
                }
            }
        )
    });
    setTimeout(function () {
        $this.submit().trigger('change');
    }, 10)


</script>
