<div class="page-margin">
    <div class="row">
        <div class="col-md-2 leftcol"><?php echo Wo_LoadPage("sidebar/left-sidebar"); ?></div>
        <div class="col-md-7 singlecol">
            <div class="page-margin wow_content mt-0">
                <div class="wo_page_hdng pag_neg_padd pag_alone">
                    <div class="wo_page_hdng_innr big_size">
                        <span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"><path fill="currentColor" d="M22,16V4A2,2 0 0,0 20,2H8A2,2 0 0,0 6,4V16A2,2 0 0,0 8,18H20A2,2 0 0,0 22,16M11,12L13.03,14.71L16,11L20,16H8M2,6V20A2,2 0 0,0 4,22H18V20H4V6"></path></svg></span>
                        Celebrity Influencer
                    </div>
                </div>
            </div>
            <div class="page-margin wow_content">
                <div class="row">
                    <div class="col-md-2">
                        <div class="celeb-avatar">
                            <img src="" class="img-fluid">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="heading">
                            <h3>Taylor Swift</h3>
                        </div>
                        <div class="location">
                            <p>16 Bluff Avenue, Watch Hill, Rhode Island</p>
                        </div>
                        <div class="curr-ranking">
                            <labe>
                                Current Ranking: 02
                            </labe>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <button type="button" class="wo_follow_btn u-see-more">Vote</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>