<?php
$page = (!empty($_GET['page-id']) && is_numeric($_GET['page-id'])) ? $_GET['page-id'] : 1;
$filter_keyword = (!empty($_GET['query'])) ? Wo_Secure($_GET['query']) : '';
$filter_type = '';
$db->pageLimit = 10;
$link = '';
if (!empty($filter_keyword)) {
    $link .= '&query=' . $filter_keyword;
    $sql = "(
    `id`        LIKE '%$filter_keyword%' OR
    `name` LIKE '%$filter_keyword%'
  )";

    $pages = $db->where($sql);
}
$sort_link = $link;
$sort_array = array('DESC_i' => array('id', 'DESC'),
    'ASC_i' => array('id', 'ASC'),
    'DESC_c' => array('name', 'DESC'),
    'ASC_c' => array('name', 'ASC'));
if (!empty($_GET['sort']) && in_array($_GET['sort'], array_keys($sort_array))) {
    $link .= "&sort=" . Wo_Secure($_GET['sort']);
    $db->orderBy($sort_array[$_GET['sort']][0], $sort_array[$_GET['sort']][1]);
} else {
    $_GET['sort'] = 'DESC_i';
    $db->orderBy('id', 'DESC');
    $pages = $db->objectbuilder()->paginate(T_GENRE, $page);
}
if (($page > $db->totalPages) && !empty($_GET['page-id'])) {
    header("Location: " . Wo_LoadAdminLinkSettings('manage-genre'));
    exit();
}

?>

<div class="container-fluid">
    <div>
        <h3>Genre</h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="#">Home</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="#">Manage Genre</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">Genres</li>
            </ol>
        </nav>
    </div>
    <!-- Vertical Layout -->
    <div class="row">
        <div class="col-lg-4 col-md-4">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Add Genre</h6>
                    <div class="row">
                        <div class="col-md-12" style="margin-bottom:0;">
                            <div class=" add_category_form_alert"></div>
                            <form method="POST" id="add_temp_cat_form">
                                <div class="row">
                                    <div class="col-md-12" id="normal-query-form">
                                        <div class="form-group form-float">
                                            <div class="form-line">
                                                <label class="form-label">Genre:</label>
                                                <input type="text" required class="form-control" name="gen_name">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="clearfix"></div>
                                    <div class="col-md-12">
                                        <div>&nbsp;</div>
                                        <button class="btn btn-info waves-effect">Add</button>
                                    </div>
                                </div>
                                <div class="clearfix"></div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-8 col-md-8">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Manage & Edit Genres</h6>
                    <div class="row">
                        <div class="col-md-10" style="margin-bottom:0;">
                            <form method="get" action="<?php echo Wo_LoadAdminLinkSettings('manage-genre'); ?>">
                                <div class="row">
                                    <div class="col-md-11">
                                        <div class="form-group form-float">
                                            <div class="form-line">
                                                <label class="form-label search-form">
                                                    Search for ID, Name.
                                                </label>
                                                <input type="text" name="query" id="query" class="form-control"
                                                       value="<?php echo($filter_keyword); ?>">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-1">
                                        <label>&nbsp;</label>
                                        <button class="btn btn-info">Search</button>
                                    </div>
                                </div>
                                <div class="clearfix"></div>
                            </form>
                        </div>
                    </div>
                    <input type="hidden" id="hash_id" name="hash_id" value="<?php echo Wo_CreateSession(); ?>">
                    <div class="clearfix"></div>
                    <div class="table-responsive">
                        <table class="table table-bordered table-striped table-hover">
                            <thead>
                            <tr>
                                <th><input type="checkbox" id="check-all" class="filled-in check-all"><label
                                            for="check-all"></label></th>
                                <th>ID</th>
                                <th>Name</th>
                                <th>Status</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php
                            foreach ($pages as $pagelist) {
                                $wo['pagelist'] = Wo_GetGenre($pagelist->id);
                                echo Wo_LoadAdminPage('manage-genre/list');
                            }
                            ?>
                            </tbody>
                        </table>
                    </div>
                    <div class="wo-admincp-feturepager">
                        <div class="pull-left">
                            <span>
                              <?php echo "Showing $page out of " . $db->totalPages; ?>
                            </span>
                        </div>
                        <div class="pull-right">
                            <nav>
                                <ul class="pagination">
                                    <li>
                                        <a href="<?php echo Wo_LoadAdminLinkSettings('manage-genre?page-id=1') . $link; ?>"
                                           data-ajax="?path=manage-genre&page-id=1<?php echo($link); ?>"
                                           class="waves-effect" title='First Page'>
                                            <i class="material-icons">first_page</i>
                                        </a>
                                    </li>
                                    <?php if ($page > 1) { ?>
                                        <li>
                                            <a href="<?php echo Wo_LoadAdminLinkSettings('manage-genre?page-id=' . ($page - 1)) . $link; ?>"
                                               data-ajax="?path=manage-genre&page-id=<?php echo($page - 1) ?><?php echo($link); ?>"
                                               class="waves-effect" title='Previous Page'>
                                                <i class="material-icons">chevron_left</i>
                                            </a>
                                        </li>
                                    <?php } ?>

                                    <?php
                                    $nums = 0;
                                    $nums_pages = ($page > 4) ? ($page - 4) : $page;

                                    for ($i = $nums_pages; $i <= $db->totalPages; $i++) {
                                        if ($nums < 20) {
                                            ?>
                                            <li class="<?php echo ($page == $i) ? 'active' : ''; ?>">
                                                <a href="<?php echo Wo_LoadAdminLinkSettings('manage-genre?page-id=' . ($i)) . $link; ?>"
                                                   data-ajax="?path=manage-genre&page-id=<?php echo($i) ?><?php echo($link); ?>"
                                                   class="waves-effect">
                                                    <?php echo $i ?>
                                                </a>
                                            </li>
                                        <?php }
                                        $nums++;
                                    } ?>

                                    <?php if ($db->totalPages > $page) { ?>
                                        <li>
                                            <a href="<?php echo Wo_LoadAdminLinkSettings('manage-genre?page-id=' . ($page + 1)) . $link; ?>"
                                               data-ajax="?path=manage-genre&page-id=<?php echo($page + 1) ?><?php echo($link); ?>"
                                               class="waves-effect" title="Next Page">
                                                <i class="material-icons">chevron_right</i>
                                            </a>
                                        </li>
                                    <?php } ?>
                                    <li>
                                        <a href="<?php echo Wo_LoadAdminLinkSettings('manage-genre?page-id=' . ($db->totalPages)) . $link; ?>"
                                           data-ajax="?path=manage-genre&page-id=<?php echo($db->totalPages) ?><?php echo($link); ?>"
                                           class="waves-effect" title='Last Page'>
                                            <i class="material-icons">last_page</i>
                                        </a>
                                    </li>
                                </ul>
                            </nav>
                        </div>
                        <div class="clearfix"></div>
                        <div class="row">
                            <div class="col-lg-4 col-md-4">
                                <span>&nbsp;</span>
                                <button type="button" class="btn btn-info waves-effect delete-selected d-block"
                                        disabled>Delete Selected<span></span></button>
                            </div>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <!-- #END# Vertical Layout -->
    <div class="modal fade" id="SelectedDeleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModal1Label"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModal1Label">Delete Genre?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Are you sure that you want to remove the selected genre?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" onclick="DeleteSelected()" data-dismiss="modal">
                        Submit
                    </button>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="DeleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModal1Label"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModal1Label">Delete Genre?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Are you sure you want to delete this genre?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" data-dismiss="modal">Delete</button>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="EditModal" tabindex="-1" role="dialog" aria-labelledby="exampleModal1Label"
         aria-hidden="true">
        <div class="modal-dialog modal-sm" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModal1Label">Edit Genre</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="edit_category_form_alert"></div>
                <form method="POST" id="edit_temp_cat_form">
                    <div class="modal-body">
                        <div id="tobeappend">

                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary waves-effect">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script>
        var add_template_category_form = $('form#add_temp_cat_form');
        var edit_template_category_form = $('form#edit_temp_cat_form');

        add_template_category_form.ajaxForm({
            url: Wo_Ajax_Requests_File() + '?f=admin_setting&s=add_genre',
            beforeSend: function () {
                add_template_category_form.find('.waves-effect').text("Please wait..");
            },
            success: function (data) {
                if (data.status == 200) {
                    add_template_category_form.find('.waves-effect').text('Save');
                    $('.add_category_form_alert').html('<div class="alert alert-success"><i class="fa fa-check"></i> ' + data.message + '</div>');
                    setTimeout(function () {
                        $('.add_category_form_alert').empty();
                        window.location.reload();
                    }, 2000);
                } else {
                    $('.add_category_form_alert').html('<div class="alert alert-danger" id="scroll"><i class="fa fa-check"></i> ' + data.message + '</div>');
                    add_template_category_form.find('.waves-effect').text("Add");
                    setTimeout(function () {
                        $('.add_category_form_alert').empty();
                    }, 5000);
                }
            }
        });

        edit_template_category_form.ajaxForm({
            url: Wo_Ajax_Requests_File() + '?f=admin_setting&s=edit_genre&hash=' + $('.main_session').val(),
            beforeSend: function () {
                edit_template_category_form.find('.waves-effect').text("Please wait..");
            },
            success: function (data) {
                if (data.status == 200) {
                    edit_template_category_form.find('.waves-effect').text('Save');
                    $('.edit_category_form_alert').html('<div class="alert alert-success"><i class="fa fa-check"></i>' + data.message +'</div>');
                    setTimeout(function () {
                        $('.edit_category_form_alert').empty();
                    }, 1000);
                    window.location.reload();
                } else {
                    $('.edit_category_form_alert').html('<div class="alert alert-danger"><i class="fa fa-check"></i> ' + data.message + '</div>');
                    edit_template_category_form.find('.waves-effect').text("Add");
                    setTimeout(function () {
                        $('.edit_category_form_alert').empty();
                    }, 5000);
                }
            }
        });

        $('.check-all').on('click', function (event) {
            $('input:checkbox').not(this).prop('checked', this.checked);
        });
        $('.delete-checkbox, .check-all').change(function (event) {
            $('.delete-selected').attr('disabled', false);
            $('.delete-selected').find('span').text(' (' + $('.delete-checkbox:checked').length + ')');
        });

        $('.delete-selected').on('click', function (event) {
            event.preventDefault();
            $('#SelectedDeleteModal').modal('show');
        });

        function DeleteSelected() {
            data = new Array();
            $('td input:checked').parents('tr').each(function () {
                data.push($(this).attr('data_selected'));
            });
            $('.delete-selected').attr('disabled', true);
            $('.delete-selected').text('Please wait..');
            $.post(Wo_Ajax_Requests_File() + "?f=admin_setting&s=remove_genre", {ids: data}, function () {
                $.each(data, function (index, value) {
                    $("#PageID_" + value).remove();
                });
                $('.delete-selected').text('Delete Selected');
            });
        }

        function Wo_DeletePage(page_id, type = 'show') {
            if (type == 'hide') {
                $('#DeleteModal').find('.btn-primary').attr('onclick', "Wo_DeletePage('" + page_id + "')");
                $('#DeleteModal').modal('show');
                return false;
            }
            hash_id = $('#hash_id').val();
            $('#PageID_' + page_id).fadeOut(300, function () {
                $(this).remove();
            });
            $.get(Wo_Ajax_Requests_File(), {
                f: 'admin_setting',
                s: 'delete_genre',
                id: page_id,
                hash_id: hash_id
            });
        }

        function Wo_EditPage(page_id, type = 'show') {
            if (type == 'hide') {
                // $.post(Wo_Ajax_Requests_File(),{f:'admin_setting',s:'get_team_page',page_id: page_id, hash_id:hash_id});
                $.ajax({
                    url: Wo_Ajax_Requests_File() + '?f=admin_setting&s=get_genre&id=' + page_id + '&hash_id=' + hash_id,
                    type: 'GET',
                    success: function (response) {
                        console.log(response);
                        $('#tobeappend').empty();
                        $('#tobeappend').append(response);
                    }
                });
                // $('#EditModal').find('.btn-primary').attr('onclick', "Wo_EditPage('"+page_id+"')");
                $('#EditModal').modal('show');
                return false;
            }
            hash_id = $('#hash_id').val();
            $('#PageID_' + page_id).fadeOut(300, function () {
                $(this).remove();
            });
            $.get(Wo_Ajax_Requests_File(), {
                f: 'admin_setting',
                s: 'delete_team_page',
                page_id: page_id,
                hash_id: hash_id
            });
        }

    </script>