<?php
$artist_categories = GetTemplateCategoriesByType('artist');
$page = (!empty($_GET['page-id']) && is_numeric($_GET['page-id'])) ? $_GET['page-id'] : 1;
$filter_keyword = (!empty($_GET['query'])) ? Wo_Secure($_GET['query']) : '';
$filter_type = '';
$db->pageLimit = 10;
$link = '';

$genres = GetGenre();


if (!empty($filter_keyword)) {
    $link .= '&query=' . $filter_keyword;
    $sql = "(
    `page_id`        LIKE '%$filter_keyword%' OR
    `username` LIKE '%$filter_keyword%' OR
    `name` LIKE '%$filter_keyword%'
  )";

    $pages = $db->where($sql);
}
$sort_link = $link;
$sort_array = array('DESC_i' => array('page_id', 'DESC'),
    'ASC_i' => array('page_id', 'ASC'),
    'DESC_c' => array('artist_category', 'DESC'),
    'ASC_c' => array('artist_category', 'ASC'));
if (!empty($_GET['sort']) && in_array($_GET['sort'], array_keys($sort_array))) {
    $link .= "&sort=" . Wo_Secure($_GET['sort']);
    $db->orderBy($sort_array[$_GET['sort']][0], $sort_array[$_GET['sort']][1]);
} else {
    $_GET['sort'] = 'DESC_i';
    $db->orderBy('page_id', 'DESC');
    $pages = $db->objectbuilder()->paginate(T_Artist_PAGES, $page);
}
if (($page > $db->totalPages) && !empty($_GET['page-id'])) {
    header("Location: " . Wo_LoadAdminLinkSettings('manage-artist-pages'));
    exit();
}

?>

<div class="container-fluid">
    <div>
        <h3>Artist/Band Pages</h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="#">Home</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="#">Manage Artist/Band</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">Artist/Band</li>
            </ol>
        </nav>
    </div>
    <!-- Vertical Layout -->
    <div class="row">
        <div class="col-lg-4 col-md-4">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Add Artist/Band</h6>
                    <div class="row">
                        <div class="col-md-12" style="margin-bottom:0;">
                            <div class=" add_category_form_alert"></div>
                            <form method="POST" id="add_teampage_form">
                                <div class="row">
                                    <div class="col-md-12" id="normal-query-form">
                                        <div class="form-group form-float">
                                            <div class="form-line">
                                                <label class="form-label">Profile Image</label>
                                                <input type="file" required class="form-control" name="logo"
                                                       accept="image/*">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-12" id="normal-query-form">
                                        <div class="form-group form-float">
                                            <div class="form-line">
                                                <label class="form-label">Profile Date:</label>
                                                <input type="date" required class="form-control" value="<?php echo date('Y-m-d') ?>" name="logo_date">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-12" id="normal-query-form">
                                        <div class="form-group form-float">
                                            <div class="form-line">
                                                <label class="form-label">Artist/Band Name:</label>
                                                <input type="text" required class="form-control" name="name">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-12 col-sm-12" id="normal-query-form">
                                        <div class="form-group form-float">
                                            <div class="form-line">
                                                <label class="form-label">Genre:</label>
                                                <select class="form-control" name="platform">
                                                    <option value="0" selected disabled>Select Genre</option>
                                                    <?php foreach ($genres as $genre){ ?>
                                                        <option value="<?php echo $genre['id'] ?>"><?php echo ucfirst($genre['name']) ?></option>
                                                    <?php } ?>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-12 col-sm-12" id="normal-query-form">
                                        <div class="form-group form-float">
                                            <div class="form-line">
                                                <label class="form-label">Artist/Band Category:</label>
                                                <select required class="form-control" name="artist_category">
                                                        <option value="0" selected disabled>Select Category</option>
                                                    <?php foreach ($artist_categories as $artist_category) { ?>
                                                        <option value="<?php echo $artist_category['id'] ?>" <?php echo $artist_category['id'] == 9 ? 'selected' : ''?>><?php echo ucfirst($artist_category['name']) ?></option>
                                                    <?php } ?>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-12" id="normal-query-form">
                                        <div class="form-group form-float">
                                            <div class="form-line">
                                                <label class="form-label">Location:</label>
                                                <input type="text" required class="form-control" name="location">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-12" id="normal-query-form">
                                        <div class="form-group form-float">
                                            <div class="form-line">
                                                <label class="form-label">Social Media:</label>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4" id="normal-query-form">
                                        <div class="form-group form-float">
                                            <div class="form-line">
                                                <label for="fb" class="form-label">Facebook:</label>
                                                <input type="checkbox" class="" value="0" name="facebook" id="fb">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4" id="normal-query-form">
                                        <div class="form-group form-float">
                                            <div class="form-line">
                                                <label for="yt" class="form-label">Youtube:</label>
                                                <input type="checkbox" class="" value="0" name="youtube" id="yt">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4" id="normal-query-form">
                                        <div class="form-group form-float">
                                            <div class="form-line">
                                                <label for="tt" class="form-label">Tiktok:</label>
                                                <input type="checkbox" class="" value="0" name="tiktok" id="tt">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-12" id="normal-query-form">
                                        <div class="form-group form-float">
                                            <div class="form-line">
                                                <label class="form-label">Twitter:</label>
                                                <input type="text" class="form-control" name="twitter">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-12" id="normal-query-form">
                                        <div class="form-group form-float">
                                            <div class="form-line">
                                                <label class="form-label">Instagram:</label>
                                                <input type="text" class="form-control" name="instagram">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-12" id="normal-query-form">
                                        <div class="form-group form-float">
                                            <div class="form-line">
                                                <label class="form-label">About:(Please add source and date at the end of the content. Thank you)</label>
                                                <textarea required class="form-control" name="about"></textarea>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-12" id="normal-query-form">
                                        <div class="form-group form-float">
                                            <div class="form-line">
                                                <label class="form-label">Sources:</label>
                                                <input type="text" required class="form-control" name="sources">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-12" id="normal-query-form">
                                        <div class="form-group form-float">
                                            <div class="form-line">
                                                <label class="form-label">Date:</label>
                                                <input type="date" required class="form-control" value="<?php echo date('Y-m-d') ?>" name="source_date">
                                            </div>
                                        </div>
                                    </div>
<!--                                    <div class="col-md-12" id="normal-query-form">-->
<!--                                        <div class="form-group form-float">-->
<!--                                            <div class="form-line">-->
<!--                                                <label class="form-label">Insta Handle:</label>-->
<!--                                                <input type="text" required class="form-control" name="username">-->
<!--                                            </div>-->
<!--                                        </div>-->
<!--                                    </div>-->
                                    <div class="col-md-12" id="normal-query-form">
                                        <div class="form-group form-float">
                                            <div class="form-line">
                                                <label class="form-label">Albums:</label>
                                                <input type="text" required class="form-control" name="albums">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-12" id="normal-query-form">
                                        <div class="form-group form-float">
                                            <div class="form-line">
                                                <label class="form-label">Music Genre(s):</label>
                                                <input type="text" required class="form-control" name="genre">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-12" id="normal-query-form">
                                        <div class="form-group form-float">
                                            <div class="form-line">
                                                <label class="form-label">Current Rank:</label>
                                                <input type="text" required class="form-control"
                                                       placeholder="To be generated dynamically" readonly>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-12" id="normal-query-form">
                                        <div class="form-group form-float">
                                            <div class="form-line">
                                                <label class="form-label">Total Influencer Points:</label>
                                                <input type="text" required class="form-control"
                                                       placeholder="To be generated dynamically" readonly>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-12 text-right ">
                                        <i class="fa fa-plus add-row" data-add="add" title="Click to add new image" style="cursor: pointer;"></i>
                                    </div>
                                    <div class="col-md-12" id="normal-query-form">
                                        <div class="form-group form-float">
                                            <div class="form-line">
                                                <label class="form-label">Gallery: (Image size should be 240X150)</label>
                                                <input type="file" required class="form-control" name="gallery[]" accept="image/*">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-10" id="normal-query-form">
                                        <div class="form-group form-float">
                                            <div class="form-line">
                                                <label class="form-label">Photo Credit:</label>
                                                <input type="text" required class="form-control"
                                                       name="photo_credit[]">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-10" id="normal-query-form">
                                            <div class="form-group form-float">
                                                <div class="form-line">
                                                    <label class="form-label">Image Capture Date:</label>
                                                    <input type="date" required class="form-control" value="<?php echo date('Y-m-d') ?>"
                                                           name="image_capture_date[]" placeholder="mm-dd-yy">
                                                </div>
                                            </div>
                                        </div>
                                    <div id="add"></div>
                                    <div class="clearfix"></div>
                                    <div class="col-md-12">
                                        <div>&nbsp;</div>
                                        <button class="btn btn-info waves-effect">Add</button>
                                    </div>
                                    <div class="col-md-12">
                                        <div class=" add_category_form_alert"></div>
                                    </div>
                                </div>
                                <div class="clearfix"></div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-8 col-md-8">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Manage & Edit Artist/Band</h6>
                    <div class="row">
                        <div class="col-md-12" style="margin-bottom:0;">
                            <form method="get" action="<?php echo Wo_LoadAdminLinkSettings('manage-artist-pages'); ?>">
                                <div class="row">
                                    <div class="col-md-9">
                                        <div class="form-group form-float">
                                            <div class="form-line">
                                                <label class="form-label search-form">
                                                    Search for ID, Name
                                                </label>
                                                <input type="text" name="query" id="query" class="form-control"
                                                       value="<?php echo($filter_keyword); ?>">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-1">
                                        <label>&nbsp;</label>
                                        <button class="btn btn-info">Search</button>
                                    </div>
                                    <div class="col-md-12">
                                        <div id="custom-alert"></div>
                                    </div>
                                </div>
                                <div class="clearfix"></div>
                            </form>
                        </div>
                    </div>
                    <input type="hidden" id="hash_id" name="hash_id" value="<?php echo Wo_CreateSession(); ?>">
                    <div class="clearfix"></div>
                    <div class="table-responsive">
                        <table class="table table-bordered table-striped table-hover">
                            <thead>
                            <tr>
                                <th><input type="checkbox" id="check-all" class="filled-in check-all"><label
                                            for="check-all"></label></th>
                                <th>ID</th>
                                <th>Name</th>
<!--                                <th>Username</th>-->
                                <th>Genre</th>
                                <th>Artist/Band Category</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php
                            foreach ($pages as $pagelist) {
                                $wo['pagelist'] = Wo_ArtistData($pagelist->page_id);
                                echo Wo_LoadAdminPage('manage-artist-pages/list');
                            }
                            ?>
                            </tbody>
                        </table>
                    </div>
                    <div class="wo-admincp-feturepager">
                        <div class="pull-left">
                            <span>
                              <?php echo "Showing $page out of " . $db->totalPages; ?>
                            </span>
                        </div>
                        <div class="pull-right">
                            <nav>
                                <ul class="pagination">
                                    <li>
                                        <a href="<?php echo Wo_LoadAdminLinkSettings('manage-artist-pages?page-id=1') . $link; ?>"
                                           data-ajax="?path=manage-artist-pages&page-id=1<?php echo($link); ?>"
                                           class="waves-effect" title='First Page'>
                                            <i class="material-icons">first_page</i>
                                        </a>
                                    </li>
                                    <?php if ($page > 1) { ?>
                                        <li>
                                            <a href="<?php echo Wo_LoadAdminLinkSettings('manage-artist-pages?page-id=' . ($page - 1)) . $link; ?>"
                                               data-ajax="?path=manage-artist-pages&page-id=<?php echo($page - 1) ?><?php echo($link); ?>"
                                               class="waves-effect" title='Previous Page'>
                                                <i class="material-icons">chevron_left</i>
                                            </a>
                                        </li>
                                    <?php } ?>

                                    <?php
                                    $nums = 0;
                                    $nums_pages = ($page > 4) ? ($page - 4) : $page;

                                    for ($i = $nums_pages; $i <= $db->totalPages; $i++) {
                                        if ($nums < 20) {
                                            ?>
                                            <li class="<?php echo ($page == $i) ? 'active' : ''; ?>">
                                                <a href="<?php echo Wo_LoadAdminLinkSettings('manage-artist-pages?page-id=' . ($i)) . $link; ?>"
                                                   data-ajax="?path=manage-artist-pages&page-id=<?php echo($i) ?><?php echo($link); ?>"
                                                   class="waves-effect">
                                                    <?php echo $i ?>
                                                </a>
                                            </li>

                                        <?php }
                                        $nums++;
                                    } ?>

                                    <?php if ($db->totalPages > $page) { ?>
                                        <li>
                                            <a href="<?php echo Wo_LoadAdminLinkSettings('manage-artist-pages?page-id=' . ($page + 1)) . $link; ?>"
                                               data-ajax="?path=manage-artist-pages&page-id=<?php echo($page + 1) ?><?php echo($link); ?>"
                                               class="waves-effect" title="Next Page">
                                                <i class="material-icons">chevron_right</i>
                                            </a>
                                        </li>
                                    <?php } ?>
                                    <li>
                                        <a href="<?php echo Wo_LoadAdminLinkSettings('manage-artist-pages?page-id=' . ($db->totalPages)) . $link; ?>"
                                           data-ajax="?path=manage-artist-pages&page-id=<?php echo($db->totalPages) ?><?php echo($link); ?>"
                                           class="waves-effect" title='Last Page'>
                                            <i class="material-icons">last_page</i>
                                        </a>
                                    </li>
                                </ul>
                            </nav>
                        </div>
                        <div class="clearfix"></div>
                        <div class="row">
                            <div class="col-lg-4 col-md-4">
                                <span>&nbsp;</span>
                                <button type="button" class="btn btn-info waves-effect delete-selected d-block"
                                        disabled>Delete Selected<span></span></button>
                            </div>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <!-- #END# Vertical Layout -->
    <div class="modal fade" id="SelectedDeleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModal1Label"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModal1Label">Delete page?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Are you sure that you want to remove the selected page?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" onclick="DeleteSelected()" data-dismiss="modal">
                        Submit
                    </button>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="DeleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModal1Label"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModal1Label">Delete Artist/Band?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Are you sure you want to delete this artist/band?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" data-dismiss="modal">Delete</button>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade bd-example-modal-lg" id="EditModal" tabindex="-1" role="dialog" aria-labelledby="exampleModal1Label"
         aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModal1Label">Edit Artist/BandPage</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="edit_category_form_alert"></div>
                <form method="POST" id="edit_teampage_form">
                    <div class="modal-body">
                        <div id="tobeappend">

                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary waves-effect">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script>
        // $(".waves-effect").click(function() {
        //     $('html, body').animate({
        //         scrollTop: $(".add_category_form_alert").offset().top
        //     }, 2000);
        // });
        // Add Row
        $(document.body).on('click', '.add-row',function (){

            var d = new Date();

            var month = d.getMonth()+1;
            var day = d.getDate();

            var output = d.getFullYear() + '-' +
                ((''+month).length<2 ? '0' : '') + month + '-' +
                ((''+day).length<2 ? '0' : '') + day;
            var attr = $(this).data('add');
            var copied_div = '<div class="row">'+
                                '<div class="col-md-12" id="normal-query-form">'+
                                    '<div class="form-group form-float">'+
                                        '<div class="form-line">'+
                                        '<input type="file" required class="form-control" name="gallery[]" accept="image/*">'+
                                        '</div>'+
                                    '</div>'+
                                '</div>'+
                                '<div class="row"> ' +
                                    '<div class="col-md-10"> ' +
                                        '<div class="form-group form-float">'+
                                            '<div class="form-line">'+
                                                '<label class="form-label">Photo Credit:</label>'+
                                                '<input type="text" required class="form-control" name="photo_credit[]">'+
                                            '</div>'+
                                        '</div>'+
                                        '<div class="form-group form-float">'+
                                            '<div class="form-line">'+
                                                '<label class="form-label">Image Capture Date:</label>'+
                                                '<input type="date" required class="form-control" name="image_capture_date[]" value="'+output+'" placeholder="mm-dd-yy">'+
                                            '</div>'+
                                        '</div>'+
                                    '</div>'+
                                    '<div class="col-md-2"> ' +
                                        '<div class=""> ' +
                                            '<div class="">'+
                                                '<i class="fa fa-times delete-row" title="Click to remove" style="cursor: pointer;margin-top: 40px;"></i>'+
                                            '</div> ' +
                                        '</div>' +
                                    '</div>'+
                                '</div>'+
                            '</div>';
            $('#'+attr).append(copied_div);
            $('.layout-wrapper .content-wrapper .content-body .content').niceScroll().resize();
        })

        $(document.body).on('click', '.delete-row', function () {
            $(this).parent().parent().parent().parent().parent().remove();
        });


        var add_category_form = $('form#add_teampage_form');
        var edit_category_form = $('form#edit_teampage_form');

        add_category_form.ajaxForm({
            url: Wo_Ajax_Requests_File() + '?f=admin_setting&s=add_artist_page',
            beforeSend: function () {
                add_category_form.find('.waves-effect').text("Please wait..");
            },
            success: function (data) {
                if (data.status == 200) {
                    add_category_form.find('.waves-effect').text('Save');
                    $('.add_category_form_alert').html('<div class="alert alert-success"><i class="fa fa-check"></i> ' + data.message + '</div>');
                    setTimeout(function () {
                        $('.add_category_form_alert').empty();
                        window.location.reload();
                    }, 2000);
                } else {
                    $('.add_category_form_alert').html('<div class="alert alert-danger" id="scroll"><i class="fa fa-check"></i> ' + data.message + '</div>');
                    add_category_form.find('.waves-effect').text("Add");
                    setTimeout(function () {
                        $('.add_category_form_alert').empty();
                    }, 5000);
                }
            }
        });

        edit_category_form.ajaxForm({
            url: Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_artist_page&hash=' + $('.main_session').val(),
            beforeSend: function () {
                edit_category_form.find('.waves-effect').text("Please wait..");
            },
            success: function (data) {
                if (data.status == 200) {
                    edit_category_form.find('.waves-effect').text('Save');
                    $('.edit_category_form_alert').html('<div class="alert alert-success"><i class="fa fa-check"></i> Category successfully edited</div>');
                    setTimeout(function () {
                        $('.edit_category_form_alert').empty();
                    }, 1000);
                    window.location.reload();
                } else {
                    $('.edit_category_form_alert').html('<div class="alert alert-danger"><i class="fa fa-check"></i> ' + data.message + '</div>');
                    edit_category_form.find('.waves-effect').text("Add");
                    setTimeout(function () {
                        $('.edit_category_form_alert').empty();
                    }, 5000);
                }
            }
        });

        $('.check-all').on('click', function (event) {
            $('input:checkbox').not(this).prop('checked', this.checked);
        });
        $('.delete-checkbox, .check-all').change(function (event) {
            $('.delete-selected').attr('disabled', false);
            $('.delete-selected').find('span').text(' (' + $('.delete-checkbox:checked').length + ')');
        });

        $('.delete-selected').on('click', function (event) {
            event.preventDefault();
            $('#SelectedDeleteModal').modal('show');
        });

        function DeleteGalleryImage(id){
            if (confirm("Are you sure you want to delete?")) {
                var id = id;
                $.post(Wo_Ajax_Requests_File() + "?f=admin_setting&s=remove_gallery_image", {id: id}, function () {
                    $('body .remove-'+id).remove();
                });
            }
            return false;
        }

        function DeleteSelected() {
            data = new Array();
            $('td input:checked').parents('tr').each(function () {
                data.push($(this).attr('data_selected'));
            });
            $('.delete-selected').attr('disabled', true);
            $('.delete-selected').text('Please wait..');
            $.post(Wo_Ajax_Requests_File() + "?f=admin_setting&s=remove_artist_page", {ids: data}, function () {
                $.each(data, function (index, value) {
                    $("#PageID_" + value).remove();
                });
                $('.delete-selected').text('Delete Selected');
            });
        }

        function Wo_DeletePage(page_id, type = 'show') {
            if (type == 'hide') {
                $('#DeleteModal').find('.btn-primary').attr('onclick', "Wo_DeletePage('" + page_id + "')");
                $('#DeleteModal').modal('show');
                return false;
            }
            hash_id = $('#hash_id').val();
            $('#PageID_' + page_id).fadeOut(300, function () {
                $(this).remove();
            });
            $.get(Wo_Ajax_Requests_File(), {
                f: 'admin_setting',
                s: 'delete_artist_page',
                page_id: page_id,
                hash_id: hash_id
            });
            var asd = "<div class='alert alert-success'>Deleted Successfully</div>";
            $('#custom-alert').html(asd);
            setTimeout(function () {
                $('#custom-alert').empty();
            }, 2000);
        }

        function Wo_EditPage(page_id, type = 'show') {
            if (type == 'hide') {
                // $.post(Wo_Ajax_Requests_File(),{f:'admin_setting',s:'get_team_page',page_id: page_id, hash_id:hash_id});
                $.ajax({
                    url: Wo_Ajax_Requests_File() + '?f=admin_setting&s=get_artist_page&page_id=' + page_id + '&hash_id=' + hash_id,
                    type: 'GET',
                    success: function (response) {
                        console.log(response);
                        $('#tobeappend').empty();
                        $('#tobeappend').append(response);
                    }
                });
                // $('#EditModal').find('.btn-primary').attr('onclick', "Wo_EditPage('"+page_id+"')");
                $('#EditModal').modal('show');
                return false;
            }
            hash_id = $('#hash_id').val();
            $('#PageID_' + page_id).fadeOut(300, function () {
                $(this).remove();
            });
            $.get(Wo_Ajax_Requests_File(), {
                f: 'admin_setting',
                s: 'delete_team_page',
                page_id: page_id,
                hash_id: hash_id
            });
        }

    </script>