<tr class="setting-pagelist" id="PageID_<?php echo $wo['pagelist']['page_id'] ?>"
    data-page-id="<?php echo $wo['pagelist']['page_id'] ?>" data_selected="<?php echo $wo['pagelist']['page_id'] ?>">
    <td><input type="checkbox" id="check-data-<?php echo $wo['pagelist']['page_id'] ?>"
               class="delete-checkbox filled-in"><label
                for="check-data-<?php echo $wo['pagelist']['page_id'] ?>"></label></td>

    <td><?php echo $wo['pagelist']['page_id']; ?></td>

    <td>
        <?php echo $wo['pagelist']['name']; ?>
    </td>
    <td>
        <?php echo $wo['pagelist']['username']; ?>
    </td>
    <td>
        <?php echo ucfirst(GetSingleGenreByID($wo['pagelist']['platform'])); ?>
    </td>
    <td>
        <?php echo ucfirst(GetSingleArtistCategory($wo['pagelist']['artist_category'])); ?>
    </td>
    <td>
        <!--      <a target = "_blank" class="btn bg-info admn_table_btn" href="-->
        <?php //echo Wo_LoadAdminLinkSettings('edit-team-pages?edit=1'); ?><!--">Edit</a>-->
        <button onclick="Wo_EditPage(<?php echo $wo['pagelist']['page_id'] ?>,'hide');" type="button" title="Edit"
                class="btn bg-info admn_table_btn"><i class="fa fa-edit"></i>
        </button>
        <button onclick="Wo_DeletePage(<?php echo $wo['pagelist']['page_id'] ?>,'hide');" type="button" title="Delete"
                class="btn bg-danger admn_table_btn"> <i class="fa fa-trash"></i>
        </button>
    </td>
</tr>