<?php
// +------------------------------------------------------------------------+
// | @author Deen Doughouz (DoughouzForest)
// | @author_url 1: http://www.wowonder.com
// | @author_url 2: http://codecanyon.net/user/doughouzforest
// | @author_email: wowondersocial@gmail.com   
// +------------------------------------------------------------------------+
// | WoWonder - The Ultimate Social Networking Platform
// | Copyright (c) 2016 WoWonder. All rights reserved.
// +------------------------------------------------------------------------+
define('T_USERS','wo_users');
define('T_COUNTRIES', 'wo_countries');
define('T_FOLLOWERS', 'wo_followers');
define('T_NOTIFICATION', 'wo_notifications');
define('T_MESSAGES', 'wo_messages');
define('T_BLOCKS', 'wo_blocks');
define('T_POSTS', 'wo_posts');
define('T_PINNED_POSTS', 'wo_pinnedPosts');
define('T_LIKES', 'wo_likes');
define('T_SAVED_POSTS', 'wo_savedPosts');
define('T_WONDERS', 'wo_wonders');
define('T_COMMENTS', 'wo_comments');
define('T_COMMENT_WONDERS', 'wo_commentWonders');
define('T_COMMENT_LIKES', 'wo_commentLikes');
define('T_HASHTAGS', 'wo_hashtags');
define('T_REPORTS', 'wo_reports');
define('T_ADS', 'wo_ads');
define('T_ANNOUNCEMENT', 'wo_announcement');
define('T_ANNOUNCEMENT_VIEWS', 'wo_announcement_views');
define('T_ACTIVITIES', 'wo_activities');
define('T_APPS', 'wo_apps');
define('T_APPS_PERMISSION', 'wo_apps_permission');
define('T_TOKENS', 'wo_tokens');
define('T_PAGES', 'wo_pages');
define('T_INFLUNCER_PAGES', 'influncer_pages');
define('T_INFLUNCER_PAGES_IMAGES', 'influencer_pages_images');
define('T_INFLUNCER_CATEGORY', 'influencer_categories');
define('T_INFLUNCER_Platform', 'influencer_platform');
define('T_Artist_PAGES', 'artist_pages');
define('T_RANKS', 'ranks');
define('T_PACKAGES', 'packages');
define('T_PACKAGES_LOGS', 'package_logs');
define('T_Artist_RANKING', 'artist_ranking');
define('T_INFLUENCER_RANKING', 'influencer_ranking');
define('T_Artist_CATEGORY', 'artist_categories');
define('T_TEMPLATE_CATEGORY', 'template_categories');
define('T_GENRE', 'genre');
define('T_ARTIST_PAGES_IMAGES', 'artist_pages_images');
define('T_TEMPLATE_COMMENTS', 'template_comments');
define('T_PAGES_LIKES', 'wo_pages_likes');
define('T_CONFIG', 'wo_config');
define('T_GROUPS', 'wo_groups');
define('T_GROUP_MEMBERS', 'wo_group_members');
define('T_VERIFICATION_REQUESTS', 'wo_verification_requests');
define('T_BANNED_IPS', 'wo_banned_ip');
define('T_GAMES', 'wo_games');
define('T_GAMES_PLAYERS', 'wo_games_players');
define('T_ALBUMS_MEDIA', 'wo_albums_media');
define('T_COMMENTS_REPLIES', 'wo_comment_replies');
define('T_COMMENT_REPLIES_LIKES', 'wo_comment_replies_likes');
define('T_COMMENT_REPLIES_WONDERS', 'wo_Comment_replies_wonders');
define('T_RECENT_SEARCHES', 'wo_recentsearches');
define('T_PAGES_INVAITES', 'wo_pages_invites');
define('T_TERMS', 'wo_terms');
define('T_EMAILS', 'wo_emails');
define('T_PAYMENTS', 'wo_payments');
define('T_CF_CATEGORIES', 'wo_classified_categories');
define('T_VIDEOS_CALLES', 'wo_videocalles');
define('T_AGORA', 'wo_agoravideocall');
define('T_APP_SESSIONS', 'wo_appssessions');
define('T_FIELDS', 'wo_profilefields');
define('T_USERS_FIELDS', 'wo_userfields');
define('T_GENERATIONS', 'generations');
define('T_PRODUCTS', 'wo_products');
define('T_PRODUCTS_MEDIA', 'wo_products_media');
define('T_POLLS', 'wo_polls');
define('T_VOTES', 'wo_votes');
define('T_CUSTOM_PAGES', 'wo_custompages');
define('T_A_REQUESTS', 'wo_affiliates_requests');
define('T_U_CHATS', 'wo_userschat');
define('T_APPS_HASH', 'wo_apps_hash');
define('T_AUDIO_CALLES', 'wo_audiocalls');
define('T_LANGS', 'wo_langs');
define('T_CODES', 'wo_codes');
define('T_BLOG', 'wo_blog');
define('T_FORUM_SEC', 'wo_forum_sections');
define('T_FORUM_THREADS', 'wo_forum_threads');
define('T_FORUMS', 'wo_forums');
define('T_FORUM_THREAD_REPLIES', 'wo_forumthreadreplies');
define('T_EVENTS', 'wo_events');
define('T_EVENTS_INV', 'wo_einvited');
define('T_EVENTS_GOING', 'wo_egoing');
define('T_EVENTS_INT', 'wo_einterested');
define('T_MOVIES', 'wo_movies');
define('T_MOVIE_COMMS', 'wo_moviecomments');
define('T_MOVIE_COMM_REPLIES', 'wo_moviecommentreplies');
define('T_BLOG_COMM', 'wo_BlogComments');
define('T_BLOG_COMM_REPLIES', 'wo_blogcommentreplies');
define('T_USER_ADS', 'wo_userads');
define('T_BM_LIKES', 'wo_blogmovielikes');
define('T_BM_DISLIKES', 'wo_blogmoviedislikes');
define('T_USER_STORY', 'wo_userstory');
define('T_USER_STORY_MEDIA', 'wo_userstorymedia');
define('T_HIDDEN_POSTS', 'wo_hiddenposts');
define('T_INVITATIONS', 'wo_admininvitations');
define('T_GROUP_ADMINS', 'wo_groupadmins');
define('T_PAGE_ADMINS', 'wo_pageadmins');
define('T_GROUP_CHAT', 'wo_GroupChat');
define('T_GROUP_CHAT_USERS', 'wo_groupchatusers');
define('T_PAGE_RATING', 'wo_pagerating');
define('T_FAMILY', 'wo_family');
define('T_REL_SHIP', 'wo_relationship');
define('T_PAYMENT_TRANSACTIONS', 'wo_payment_transactions');
define('T_USERADS_DATA', 'wo_userads_data');
define('T_POKES', 'wo_pokes');
define('T_GIFTS', 'wo_gifts');
define('T_USERGIFTS', 'wo_user_gifts');
define('T_STICKERS', 'wo_stickers');
define('T_REACTIONS', 'wo_reactions');
define('T_STORY_SEEN', 'wo_story_seen');
define('T_MANAGE_PRO', 'wo_manage_pro');
define('T_PAGES_CATEGORY', 'wo_pages_categories');
define('T_GROUPS_CATEGORY', 'wo_groups_categories');
define('T_BLOGS_CATEGORY', 'wo_blogs_categories');
define('T_PRODUCTS_CATEGORY', 'wo_products_categories');
define('T_JOB_CATEGORY', 'wo_job_categories');
define('T_BANK_TRANSFER', 'bank_receipts');
define('T_COLORS', 'wo_colored_posts');
define('T_ADMIN', 'wo_admin_pages');
define('T_GENDER', 'wo_gender');
define('T_JOB', 'wo_job');
define('T_JOB_APPLY', 'wo_job_apply');
define('T_BLOG_REACTION', 'wo_blog_reaction');
define('T_FUNDING', 'wo_funding');
define('T_FUNDING_RAISE', 'wo_funding_raise');
define('T_REACTIONS_TYPES', 'wo_reactions_types');
define('T_SUB_CATEGORIES', 'wo_sub_categories');
define('T_CUSTOM_FIELDS', 'wo_custom_fields');
define('T_REFUND', 'wo_refund');
define('T_OFFER', 'wo_offers');
define('T_BAD_LOGIN', 'wo_bad_login');
define('T_INVITAION_LINKS', 'wo_invitation_links');
define('T_LIVE_SUB', 'wo_live_sub_users');











// define('T_USERS','Wo_Users');
// define('T_COUNTRIES', 'Wo_Countries');
// define('T_FOLLOWERS', 'Wo_Followers');
// define('T_NOTIFICATION', 'Wo_Notifications');
// define('T_MESSAGES', 'Wo_Messages');
// define('T_BLOCKS', 'Wo_Blocks');
// define('T_POSTS', 'Wo_Posts');
// define('T_PINNED_POSTS', 'Wo_PinnedPosts');
// define('T_LIKES', 'Wo_Likes');
// define('T_SAVED_POSTS', 'Wo_SavedPosts');
// define('T_WONDERS', 'Wo_Wonders');
// define('T_COMMENTS', 'Wo_Comments');
// define('T_COMMENT_WONDERS', 'Wo_CommentWonders');
// define('T_COMMENT_LIKES', 'Wo_CommentLikes');
// define('T_HASHTAGS', 'Wo_Hashtags');
// define('T_REPORTS', 'Wo_Reports');
// define('T_ADS', 'Wo_Ads');
// define('T_ANNOUNCEMENT', 'Wo_Announcement');
// define('T_ANNOUNCEMENT_VIEWS', 'Wo_Announcement_Views');
// define('T_ACTIVITIES', 'Wo_Activities');
// define('T_APPS', 'Wo_Apps');
// define('T_APPS_PERMISSION', 'Wo_Apps_Permission');
// define('T_TOKENS', 'Wo_Tokens');
// define('T_PAGES', 'Wo_Pages');
// define('T_PAGES_LIKES', 'Wo_Pages_Likes');
// define('T_CONFIG', 'Wo_Config');
// define('T_GROUPS', 'Wo_Groups');
// define('T_GROUP_MEMBERS', 'Wo_Group_Members');
// define('T_VERIFICATION_REQUESTS', 'Wo_Verification_Requests');
// define('T_BANNED_IPS', 'Wo_Banned_Ip');
// define('T_GAMES', 'Wo_Games');
// define('T_GAMES_PLAYERS', 'Wo_Games_Players');
// define('T_ALBUMS_MEDIA', 'Wo_Albums_Media');
// define('T_COMMENTS_REPLIES', 'Wo_Comment_Replies');
// define('T_COMMENT_REPLIES_LIKES', 'Wo_Comment_Replies_Likes');
// define('T_COMMENT_REPLIES_WONDERS', 'Wo_Comment_Replies_Wonders');
// define('T_RECENT_SEARCHES', 'Wo_RecentSearches');
// define('T_PAGES_INVAITES', 'Wo_Pages_Invites');
// define('T_TERMS', 'Wo_Terms');
// define('T_EMAILS', 'Wo_Emails');
// define('T_PAYMENTS', 'Wo_Payments');
// define('T_CF_CATEGORIES', 'Wo_Classified_Categories');
// define('T_VIDEOS_CALLES', 'Wo_VideoCalles');
// define('T_AGORA', 'Wo_AgoraVideoCall');
// define('T_APP_SESSIONS', 'Wo_AppsSessions');
// define('T_FIELDS', 'Wo_ProfileFields');
// define('T_USERS_FIELDS', 'Wo_UserFields');
// define('T_PRODUCTS', 'Wo_Products');
// define('T_PRODUCTS_MEDIA', 'Wo_Products_Media');
// define('T_POLLS', 'Wo_Polls');
// define('T_VOTES', 'Wo_Votes');
// define('T_CUSTOM_PAGES', 'Wo_CustomPages');
// define('T_A_REQUESTS', 'Wo_Affiliates_Requests');
// define('T_U_CHATS', 'Wo_UsersChat');
// define('T_APPS_HASH', 'Wo_Apps_Hash');
// define('T_AUDIO_CALLES', 'Wo_AudioCalls');
// define('T_LANGS', 'Wo_Langs');
// define('T_CODES', 'Wo_Codes');
// define('T_BLOG', 'Wo_Blog');
// define('T_FORUM_SEC', 'Wo_Forum_Sections');
// define('T_FORUM_THREADS', 'Wo_Forum_Threads');
// define('T_FORUMS', 'Wo_Forums');
// define('T_FORUM_THREAD_REPLIES', 'Wo_ForumThreadReplies');
// define('T_EVENTS', 'Wo_Events');
// define('T_EVENTS_INV', 'Wo_Einvited');
// define('T_EVENTS_GOING', 'Wo_Egoing');
// define('T_EVENTS_INT', 'Wo_Einterested');
// define('T_MOVIES', 'Wo_Movies');
// define('T_MOVIE_COMMS', 'Wo_MovieComments');
// define('T_MOVIE_COMM_REPLIES', 'Wo_MovieCommentReplies');
// define('T_BLOG_COMM', 'Wo_BlogComments');
// define('T_BLOG_COMM_REPLIES', 'Wo_BlogCommentReplies');
// define('T_USER_ADS', 'Wo_UserAds');
// define('T_BM_LIKES', 'Wo_BlogMovieLikes');
// define('T_BM_DISLIKES', 'Wo_BlogMovieDisLikes');
// define('T_USER_STORY', 'Wo_UserStory');
// define('T_USER_STORY_MEDIA', 'Wo_UserStoryMedia');
// define('T_HIDDEN_POSTS', 'Wo_HiddenPosts');
// define('T_INVITATIONS', 'Wo_AdminInvitations');
// define('T_GROUP_ADMINS', 'Wo_GroupAdmins');
// define('T_PAGE_ADMINS', 'Wo_PageAdmins');
// define('T_GROUP_CHAT', 'Wo_GroupChat');
// define('T_GROUP_CHAT_USERS', 'Wo_GroupChatUsers');
// define('T_PAGE_RATING', 'Wo_PageRating');
// define('T_FAMILY', 'Wo_Family');
// define('T_REL_SHIP', 'Wo_Relationship');
// define('T_PAYMENT_TRANSACTIONS', 'Wo_Payment_Transactions');
// define('T_USERADS_DATA', 'Wo_UserAds_Data');
// define('T_POKES', 'Wo_Pokes');
// define('T_GIFTS', 'Wo_Gifts');
// define('T_USERGIFTS', 'Wo_User_Gifts');
// define('T_STICKERS', 'Wo_Stickers');
// define('T_REACTIONS', 'Wo_Reactions');
// define('T_STORY_SEEN', 'Wo_Story_Seen');
// define('T_MANAGE_PRO', 'Wo_Manage_Pro');
// define('T_PAGES_CATEGORY', 'Wo_Pages_Categories');
// define('T_GROUPS_CATEGORY', 'Wo_Groups_Categories');
// define('T_BLOGS_CATEGORY', 'Wo_Blogs_Categories');
// define('T_PRODUCTS_CATEGORY', 'Wo_Products_Categories');
// define('T_JOB_CATEGORY', 'Wo_Job_Categories');
// define('T_BANK_TRANSFER', 'bank_receipts');
// define('T_COLORS', 'Wo_Colored_Posts');
// define('T_ADMIN', 'Wo_Admin_Pages');
// define('T_GENDER', 'Wo_Gender');
// define('T_JOB', 'Wo_Job');
// define('T_JOB_APPLY', 'Wo_Job_Apply');
// define('T_BLOG_REACTION', 'Wo_Blog_Reaction');
// define('T_FUNDING', 'Wo_Funding');
// define('T_FUNDING_RAISE', 'Wo_Funding_Raise');
// define('T_REACTIONS_TYPES', 'Wo_Reactions_Types');
// define('T_SUB_CATEGORIES', 'Wo_Sub_Categories');
// define('T_CUSTOM_FIELDS', 'Wo_Custom_Fields');
// define('T_REFUND', 'Wo_Refund');
// define('T_OFFER', 'Wo_Offers');
// define('T_BAD_LOGIN', 'Wo_Bad_Login');
// define('T_INVITAION_LINKS', 'Wo_Invitation_Links');
// define('T_LIVE_SUB', 'Wo_Live_Sub_Users');
?>