<div class="container-fluid">
    <div>
        <h3>Manage Features</h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="#">Home</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="#">Settings</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">Manage Features</li>
            </ol>
        </nav>
    </div>
    <!-- Vertical Layout -->
    <div class="row">
        <div class="col-lg-7 col-md-7">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Site Features</h6>
                    <div class="site-settings-alert"></div>
                    <form class="site-settings" method="POST">
                        <label for="afternoon_system">Greeting System<span class="black" data-toggle="popover" data-trigger="hover" data-content="Good Afternoon, good morning messages."><i class="fa fa-question-circle fa-fw"></i></span></label>
                        <div class="form-group">
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="afternoon_system" id="afternoon_system-enabled" value="1" <?php echo ($wo['config']['afternoon_system'] == 1) ? 'checked': '';?>>
                                <label  class="form-check-label" for="afternoon_system-enabled">Enabled</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="afternoon_system" id="afternoon_system-disabled" value="0" <?php echo ($wo['config']['afternoon_system'] == 0) ? 'checked': '';?>>
                                <label  class="form-check-label" for="afternoon_system-disabled" class="m-l-20">Disabled</label>
                            </div>
                        </div>
                        <label for="poke_system">Poke System<span class="black" data-toggle="popover" data-trigger="hover" data-content="Poke System"><i class="fa fa-question-circle fa-fw"></i></span></label>
                        <div class="form-group">
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="poke_system" id="poke_system-enabled" value="1" <?php echo ($wo['config']['poke_system'] == 1) ? 'checked': '';?>>
                                <label  class="form-check-label" for="poke_system-enabled">Enabled</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="poke_system" id="poke_system-disabled" value="0" <?php echo ($wo['config']['poke_system'] == 0) ? 'checked': '';?>>
                                <label  class="form-check-label" for="poke_system-disabled" class="m-l-20">Disabled</label>
                            </div>
                        </div>
                        <label for="pages">Pages System <span class="black" data-toggle="popover" data-trigger="hover" data-content="Allow users to create fan pages."><i class="fa fa-question-circle fa-fw"></i></span></label>
                        <div class="form-group">
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="pages" id="pages-enabled" value="1" <?php echo ($wo['config']['pages'] == 1) ? 'checked': '';?>>
                                <label  class="form-check-label" for="pages-enabled">Enabled</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="pages" id="pages-disabled" value="0" <?php echo ($wo['config']['pages'] == 0) ? 'checked': '';?>>
                                <label  class="form-check-label" for="pages-disabled" class="m-l-20">Disabled</label>
                            </div>
                        </div>
                        <label for="groups">Groups System <span class="black" data-toggle="popover" data-trigger="hover" data-content="Allow users to create groups."><i class="fa fa-question-circle fa-fw"></i></span></label>
                        <div class="form-group">
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="groups" id="groups-enabled" value="1" <?php echo ($wo['config']['groups'] == 1) ? 'checked': '';?>>
                                <label  class="form-check-label" for="groups-enabled">Enabled</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="groups" id="groups-disabled" value="0" <?php echo ($wo['config']['groups'] == 0) ? 'checked': '';?>>
                                <label  class="form-check-label" for="groups-disabled" class="m-l-20">Disabled</label>
                            </div>
                        </div>
                        <label for="blogs">Blogs System <span class="black" data-toggle="popover" data-trigger="hover" data-content="Allow users to create blogs."><i class="fa fa-question-circle fa-fw"></i></span></label>
                        <div class="form-group">
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="blogs" id="blogs-enabled" value="1" <?php echo ($wo['config']['blogs'] == 1) ? 'checked': '';?>>
                                <label  class="form-check-label" for="blogs-enabled">Enabled</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="blogs" id="blogs-disabled" value="0" <?php echo ($wo['config']['blogs'] == 0) ? 'checked': '';?>>
                                <label  class="form-check-label" for="blogs-disabled" class="m-l-20">Disabled</label>
                            </div>
                        </div>
                        <label for="can_blogs">Who Can Post Blogs? </label>
                        <div class="form-group">
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="can_blogs" id="can_blogs-enabled" value="0" <?php echo ($wo['config']['can_blogs'] == 0) ? 'checked': '';?>>
                                <label  class="form-check-label" for="can_blogs-enabled">Admins</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="can_blogs" id="can_blogs-disabled" value="1" <?php echo ($wo['config']['can_blogs'] == 1) ? 'checked': '';?>>
                                <label  class="form-check-label" for="can_blogs-disabled" class="m-l-20">Users</label>
                            </div>
                        </div>
                        <label for="blog_approval">Blog Approval System</label>
                        <div class="form-group">
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="blog_approval" id="blog_approval-enabled" value="1" <?php echo ($wo['config']['blog_approval'] == 1) ? 'checked': '';?>>
                                <label  class="form-check-label" for="blog_approval-enabled">Enabled</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="blog_approval" id="blog_approval-disabled" value="0" <?php echo ($wo['config']['blog_approval'] == 0) ? 'checked': '';?>>
                                <label  class="form-check-label" for="blog_approval-disabled" class="m-l-20">Disabled</label>
                            </div>
                        </div>

                        <label for="events">Events System <span class="black" data-toggle="popover" data-trigger="hover" data-content="Allow Events System."><i class="fa fa-question-circle fa-fw"></i></span></label>
                        <div class="form-group">
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="events" id="events-enabled" value="1" <?php echo ($wo['config']['events'] == 1) ? 'checked': '';?>>
                                <label  class="form-check-label" for="events-enabled">Enabled</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="events" id="events-disabled" value="0" <?php echo ($wo['config']['events'] == 0) ? 'checked': '';?>>
                                <label  class="form-check-label" for="events-disabled" class="m-l-20">Disabled</label>
                            </div>
                        </div>
                        <label for="events_visibility">Events System Visibility<span class="black" data-toggle="popover" data-trigger="hover" data-content="Who can see events?"><i class="fa fa-question-circle fa-fw"></i></span></label>
                        <div class="form-group">
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="events_visibility" id="events_visibility-enabled" value="1" <?php echo ($wo['config']['events_visibility'] == 1) ? 'checked': '';?>>
                                <label  class="form-check-label" for="events_visibility-enabled">Registered Users</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="events_visibility" id="events_visibility-disabled" value="0" <?php echo ($wo['config']['events_visibility'] == 0) ? 'checked': '';?>>
                                <label  class="form-check-label" for="events_visibility-disabled" class="m-l-20">Unregistered Users</label>
                            </div>
                        </div>
                        <label for="forum_visibility" class="d-none">Forums System Visibility<span class="black" data-toggle="popover" data-trigger="hover" data-content="Who can see forums?"><i class="fa fa-question-circle fa-fw"></i></span></label>
                        <div class="form-group d-none">
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="forum_visibility" id="forum_visibility-enabled" value="1" <?php echo ($wo['config']['forum_visibility'] == 1) ? 'checked': '';?>>
                                <label  class="form-check-label" for="forum_visibility-enabled">Registered Users</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="forum_visibility" id="forum_visibility-disabled" value="0" <?php echo ($wo['config']['forum_visibility'] == 0) ? 'checked': '';?>>
                                <label  class="form-check-label" for="forum_visibility-disabled" class="m-l-20">Unregistered Users</label>
                            </div>
                        </div>
                        <label for="user_status">Story / Status System <span class="black" data-toggle="popover" data-trigger="hover" data-content="Allow users to create stories & status."><i class="fa fa-question-circle fa-fw"></i></span></label>
                        <div class="form-group">
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="user_status" id="user_status-enabled" value="1" <?php echo ($wo['config']['user_status'] == 1) ? 'checked': '';?>>
                                <label  class="form-check-label" for="user_status-enabled">Enabled</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="user_status" id="user_status-disabled" value="0" <?php echo ($wo['config']['user_status'] == 0) ? 'checked': '';?>>
                                <label  class="form-check-label" for="user_status-disabled" class="m-l-20">Disabled</label>
                            </div>
                        </div>
                        <label for="stickers">GIF System <span class="black" data-toggle="popover" data-trigger="hover" data-content="Allow users to share gif images."><i class="fa fa-question-circle fa-fw"></i></span></label>
                        <div class="form-group">
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="stickers" id="stickers-enabled" value="1" <?php echo ($wo['config']['stickers'] == 1) ? 'checked': '';?>>
                                <label  class="form-check-label" for="stickers-enabled">Enabled</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="stickers" id="stickers-disabled" value="0" <?php echo ($wo['config']['stickers'] == 0) ? 'checked': '';?>>
                                <label  class="form-check-label" for="stickers-disabled" class="m-l-20">Disabled</label>
                            </div>
                        </div>

                        <label for="popular_posts">Popular Posts & Comments (Shows in header)</label>
                        <div class="form-group">
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="popular_posts" id="popular_posts-enabled" value="1" <?php echo ($wo['config']['popular_posts'] == 1) ? 'checked': '';?>>
                                <label  class="form-check-label" for="popular_posts-enabled">Enabled</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="popular_posts" id="popular_posts-disabled" value="0" <?php echo ($wo['config']['popular_posts'] == 0) ? 'checked': '';?>>
                                <label  class="form-check-label" for="popular_posts-disabled" class="m-l-20">Disabled</label>
                            </div>
                        </div>

                        <label for="google_map">Google Maps (Posts, Profile, Settings, Ads) <span class="black" data-toggle="popover" data-trigger="hover" data-content="Note: This doesn't disable the map system, it disables google auto complete API."><i class="fa fa-question-circle fa-fw"></i></span></label>
                        <div class="form-group">
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="google_map" id="google_map-enabled" value="1" <?php echo ($wo['config']['google_map'] == 1) ? 'checked': '';?>>
                                <label  class="form-check-label" for="google_map-enabled">Enabled</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="google_map" id="google_map-disabled" value="0" <?php echo ($wo['config']['google_map'] == 0) ? 'checked': '';?>>
                                <label  class="form-check-label" for="google_map-disabled" class="m-l-20">Disabled</label>
                            </div>
                        </div>

                        <label for="password_complexity_system">Password Complexity System</label>
                        <div class="form-group">
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="password_complexity_system" id="password_complexity_system-enabled" value="1" <?php echo ($wo['config']['password_complexity_system'] == 1) ? 'checked': '';?>>
                                <label  class="form-check-label" for="password_complexity_system-enabled">Enabled</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="password_complexity_system" id="password_complexity_system-disabled" value="0" <?php echo ($wo['config']['password_complexity_system'] == 0) ? 'checked': '';?>>
                                <label  class="form-check-label" for="password_complexity_system-disabled" class="m-l-20">Disabled</label>
                            </div>
                        </div>

                        <label for="notify_new_post">Notification When User Create New Post</label>
                        <div class="form-group">
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="notify_new_post" id="notify_new_post-enabled" value="1" <?php echo ($wo['config']['notify_new_post'] == 1) ? 'checked': '';?>>
                                <label  class="form-check-label" for="notify_new_post-enabled">Enabled</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="notify_new_post" id="notify_new_post-disabled" value="0" <?php echo ($wo['config']['notify_new_post'] == 0) ? 'checked': '';?>>
                                <label  class="form-check-label" for="notify_new_post-disabled" class="m-l-20">Disabled</label>
                            </div>
                        </div>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                        <button type="submit" class="btn btn-primary m-t-15 waves-effect">Save</button>
                    </form>
                </div>
            </div>
        </div>

        <div class="col-lg-3 col-md-3" id="point_level_system_div">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Point & level system settings</h6>
                    <div class="site-settings-alert2"></div>
                    <form class="site-settings2" method="POST">
                        <label for="point_allow_withdrawal">Allow user to withdrawal those money</label>
                        <div class="form-group">
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="point_allow_withdrawal" id="point_allow_withdrawal-enabled" value="1" <?php echo ($wo['config']['point_allow_withdrawal'] == 1) ? 'checked': '';?>>
                                <label  class="form-check-label" for="point_allow_withdrawal-enabled">Enabled</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="point_allow_withdrawal" id="point_allow_withdrawal-disabled" value="0" <?php echo ($wo['config']['point_allow_withdrawal'] == 0) ? 'checked': '';?>>
                                <label  class="form-check-label" for="point_allow_withdrawal-disabled" class="m-l-20">Disabled</label>
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">$1.00 = ? Point</label>
                                <input type="text" name="dollar_to_point_cost" class="form-control" value="<?php echo $wo['config']['dollar_to_point_cost']?>">
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Comments</label>
                                <input type="text" name="comments_point" class="form-control" value="<?php echo $wo['config']['comments_point']?>">
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Likes</label>
                                <input type="text" name="likes_point" class="form-control" value="<?php echo $wo['config']['likes_point']?>">
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">DisLikes</label>
                                <input type="text" name="dislikes_point" class="form-control" value="<?php echo $wo['config']['dislikes_point']?>">
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Wonders</label>
                                <input type="text" name="wonders_point" class="form-control" value="<?php echo $wo['config']['wonders_point']?>">
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Reaction</label>
                                <input type="text" name="reaction_point" class="form-control" value="<?php echo $wo['config']['reaction_point']?>">
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Create Post</label>
                                <input type="text" name="createpost_point" class="form-control" value="<?php echo $wo['config']['createpost_point']?>">
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Create Blog</label>
                                <input type="text" name="createblog_point" class="form-control" value="<?php echo $wo['config']['createblog_point']?>">
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Free users daily limit</label>
                                <input type="text" name="free_day_limit" class="form-control" value="<?php echo $wo['config']['free_day_limit']?>">
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">pro users daily limit</label>
                                <input type="text" name="pro_day_limit" class="form-control" value="<?php echo $wo['config']['pro_day_limit']?>">
                            </div>
                        </div>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                        <button type="submit" class="btn btn-primary m-t-15 waves-effect">Save</button>
                    </form>
                </div>
            </div>
        </div>

        <div class="clearfix"></div>
    </div>
    <!-- #END# Vertical Layout -->
    <script>
        $(function() {

            <?php if ($wo['config']['point_level_system'] == 0){?>
            $( '#point_level_system_div' ).hide();
            <?php } ?>

            $('input[type=radio][name=point_level_system]').change(function(){
                var point_level_system_selected_option = $('#point_level_system option:selected').attr('value');

                if( this.value == 1 ){
                    $( '#point_level_system_div' ).show();
                }

                if( this.value == 0 ){
                    $( '#point_level_system_div' ).hide();
                }
            });

            var form_site_settings = $('form.site-settings');
            form_site_settings.ajaxForm({
                url: Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_general_setting',
                beforeSend: function() {
                    form_site_settings.find('button').text('Please wait..');
                },
                success: function(data) {
                    if (data.status == 200) {
                        form_site_settings.find('button').text('Save');
                        $("html, body").animate({ scrollTop: 0 }, "slow");
                        $('.site-settings-alert').html('<div class="alert alert-success"><i class="fa fa-check"></i> Settings updated successfully</div>');
                        setTimeout(function () {
                            $('.site-settings-alert').empty();
                        }, 2000);
                    }
                }
            });

            var form_site_settings2 = $('form.site-settings2');

            form_site_settings2.ajaxForm({
                url: Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_general_setting',
                beforeSubmit : function(arr, $form, options){
                    arr.push({name:'point_level_system', value: 1});
                },
                beforeSend: function() {
                    form_site_settings2.find('#point_allow_withdrawal-disabled').removeAttr('checked');
                    form_site_settings2.find('#point_allow_withdrawal-enabled').attr('checked',true);
                    form_site_settings2.find('button').text('Please wait..');
                },
                success: function(data) {
                    if (data.status == 200) {
                        form_site_settings2.find('button').text('Save');
                        $("html, body").animate({ scrollTop: 0 }, "slow");
                        $('.site-settings-alert2').html('<div class="alert alert-success"><i class="fa fa-check"></i> Settings updated successfully</div>');
                        setTimeout(function () {
                            $('.site-settings-alert2').empty();
                        }, 2000);
                    }
                }
            });

        });

    </script>